### ISSUE TITLE
Make a front page

### ISSUE THREAD

**Issue by arschles** [ahmetb/go-httpbin#12]
In https://github.com/arschles/kubehttpin, I am serving go-httpbin on the internet. It'd be nice to have a home page that contains a description of what this repository does. Similar to what's under the ["Endpoints" section of the README](https://github.com/ahmetb/go-httpbin#endpoints) or what's at http://httpbin.org/

**Comment by ahmetb** [comment]
Perhaps we can just say Hello World and leave a link to the README?

**Comment by arschles** [comment]
Works for me!
